#!/bin/sh
cp -ra /gk802_components /target/
mount --bind /proc /target/proc
chroot /target /gk802_components/install_kernel_uboot.sh > /target/var/log/gk802_install_kernel_uboot.log 2>&1
umount /target/proc
rm -rf /target/gk802_components
